---
platform: linux

image_resource:
  type: docker-image
  source: {repository: rowanto/docker-java8-mvn-nodejs-npm}

inputs:
  - name: azure-cd-pipeline-repo

run:
  path: azure-cd-pipeline-sample/ci/scripts/build.sh